spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wattpilot}
    username: ${DB_USERNAME:wattpilot}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
